export enum StorageKeyEnum {
    adminUsername = 'adminUsername',
    adminPassword = 'adminPassword',
    lastSftpStatus = 'lastSftpStatus',
    isBackgroundMode = 'backgroundMode',
    logoPath = 'logoPath',
    kioskModeModalDuration = 'kioskModeModalDuration',
    kioskModeMessage = 'kioskModeMessage',
    kioskModeCommunication = 'kioskModeCommunication',
    clockingSoundVolume = 'clockingSoundVolume',
    clockingStoringDuration = 'clockingStoringDuration',
    clockingDisplayDuration = 'clockingDisplayDuration',
    delayBetweenTwoClocking = 'delayBetweenTwoClocking',
    sftpServerName = 'sftpServerName',
    sftpPort = 'sftpPort',
    sftpUsername = 'sftpUsername',
    sftpPassword = 'sftpPassword',
    sftpSavePath = 'sftpSavePath',
    synchronisationFrequency = 'synchronisationFrequency',
    synchronisationBeginTime = 'synchronisationBeginTime',
    lastSynchronisationDatetime = 'lastSynchronisationDatetime',
    nextSynchronisationDatetime = 'nextSynchronisationDatetime',
}
